
import React from 'react';
import { DevelopmentSection } from './components/DevelopmentSection';
import { CollaborationSection } from './components/CollaborationSection';
import { AutomationSection } from './components/AutomationSection';
import { SecuritySection } from './components/SecuritySection';
import { GithubIcon } from './components/icons';

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-background font-sans">
      <header className="py-6 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto flex items-center space-x-4">
          <GithubIcon className="h-10 w-10 text-accent" />
          <div>
            <h1 className="text-3xl font-bold text-text-primary leading-tight">GitHub & Actions KPI Dashboard</h1>
            <p className="text-text-secondary mt-1">Key Performance Indicators for Engineering Excellence</p>
          </div>
        </div>
      </header>
      <main className="py-6 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <DevelopmentSection />
          <CollaborationSection />
          <AutomationSection />
          <SecuritySection />
        </div>
      </main>
      <footer className="text-center py-4 text-text-secondary text-sm">
        <p>Dashboard generated by World-Class Senior Frontend React Engineer</p>
      </footer>
    </div>
  );
};

export default App;
